[tool.ruff]
# Select which rules to enable (see https://docs.astral.sh/ruff/rules/)
select = [
    "E",    # pycodestyle errors (e.g., whitespace, indentation)
    "F",    # Pyflakes (e.g., unused imports, variables)
    "W",    # pycodestyle warnings
    "I",    # isort (import sorting)
    "N",    # pep8-naming (naming conventions)
    "D",    # pydocstyle (docstring conventions)
    "UP",   # pyupgrade (modernize syntax)
    "C90",  # mccabe (complexity)
    "T201", # print statement in production
    "B",    # flake8-bugbear (common bugs)
]

# Optionally, ignore some rules
ignore = [
  "E501", # Ignore line length errors
]

# Set a max line length
line-length = 88

# Target Python version
target-version = "py39"

# Exclude some files/folders from linting
exclude = [
    ".venv",
    "build",
    "dist",
    "migrations",
]

# Example: Enable autofix on some rules (when running ruff --fix)
fixable = ["E", "F", "I", "UP", "B"]

# Example: Enable only a subset of rules for specific files
[tool.ruff.per-file-ignores]
"tests/*" = ["D", "E501"]  # Ignore docstring and line length errors in tests
